"""
This file contains the models for the Neo4j integration which is to allow users to query the Neo4j database directly using natural language or Cypher queries.
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any


# This creates a model called 'NaturalLanguageQueryRequest' that defines what a request to the Neo4j query endpoint should look like
class NaturalLanguageQueryRequest(BaseModel):
    """Request model for natural language to Cypher query"""
    
    
    question: str = Field(
        ...,
        description="Natural language question about Active Directory",
        min_length=5
    )
    
    # This is a boolean field that allows the user to request remediation for the findings found in the query
    # This is used to generate a remediation for the findings found in the query ( for example: if a user has local administrator rights on a computer, a remediation could be to remove the user from the computer )
    
    include_remediation: bool = Field(
        default=False,
        description="Whether to generate remediation for findings"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "question": "Find all paths to Domain Admins",
                "include_remediation": False
            }
        }


# This creates a model called 'CypherQueryRequest' that defines what a request to the Neo4j query endpoint should look like
class CypherQueryRequest(BaseModel):
    """Request model for direct Cypher query execution"""
    
    cypher: str = Field(
        ...,
        description="Cypher query to execute",
        min_length=10
    )
    
    limit: Optional[int] = Field(
        100,
        description="Maximum number of results to return",
        ge=1,
        le=1000
    )
    
    
    class Config:
        """
        json_schema_extra: This is a dictionary that contains the example of the request and what it should look like in the autogenerated documentation.
        
        Fun fact ( This part of the comment will now just be used to explain cypher queries and what they do ) 
        Adminto: This is a relationship in BloodHound that represents that a user has local administrator rights on a computer.
        Adminto relationships are high risk relationships because local-admins can:
            - Dump credentials from memory
            - They can install malware
            - They can pivot to other systems | computers
        
        User: This is a node in BloodHound that represents a user.
        Computer: This is a node in BloodHound that represents a computer.
        
        So the cypher query can be read as: "Match all users that have an AdminTo relationship to a computer and return the name of the user and the name of the computer. Limit the results to 10."
        """
        json_schema_extra = {
            "example": {
                "cypher": "MATCH (u:User)-[:AdminTo]->(c:Computer) RETURN u.name, c.name LIMIT 10",
                "limit": 100
            }
        }


# This creates a model called 'Neo4jQueryResponse' that defines what a response from the Neo4j query endpoint should look like
class Neo4jQueryResponse(BaseModel):
    """Response model for Neo4j queries"""
    
    question: Optional[str] = Field(
        None,
        description="Original question (for natural language queries)"
    )
    
    cypher_query: str = Field(
        ...,
        description="Cypher query that was executed"
    )
    
    results: List[Dict[str, Any]] = Field(
        ...,
        description="Query results"
    )
    
    count: int = Field(
        ...,
        description="Number of results returned"
    )
    
    explanation: Optional[str] = Field(
        None,
        description="Model's explanation of the results"
    )
    
    remediations: Optional[List[Dict[str, Any]]] = Field(
        None,
        description="Remediation suggestions if requested"
    )


# This creates a model called 'Neo4jConnectionTest' that defines what a response from the Neo4j connection test endpoint should look like
# This endpoint is used to test if the connection to the Neo4j database is successful
class Neo4jConnectionTest(BaseModel):
    """Response model for connection test"""
    
    connected: bool = Field(
        ...,
        description="Whether connection to Neo4j is successful"
    )
    
    database: Optional[str] = Field(
        None,
        description="Connected database name"
    )
    
    node_count: Optional[int] = Field(
        None,
        description="Total number of nodes in database"
    )
    
    relationship_count: Optional[int] = Field(
        None,
        description="Total number of relationships in database"
    )
    
    error: Optional[str] = Field(
        None,
        description="Error message if connection failed"
    )