"""
Basically structures the response from the api so that it is consistent and easy to understand.
"""

from pydantic import BaseModel, Field
from typing import List

# This creates a model called 'QueryResponse' that defines what a response from the api should look like

class QueryResponse(BaseModel):
    """
    Response model for the query endpoint
    This model defines the structure of the response from the query endpoint
    It includes the answer to the question and the sources used to generate the answer and how it should be formatted
    and written in the automatically generated documentation.
    
    '...': the three dots mean that the field is required and must be provided when the model is used
    'description': Explains the field and what it is used for in the autogenerated documentation.
    'example': Provides an example of the field and what it should look like in the autogenerated documentation.
    
    """
    answer: str = Field(..., description="The answer generated by the system", example="The AdminTo edge in BloodHound represents administrative privileges from one object to another within an Active Directory environment.")
    sources: List[str] = Field(..., description="List of sources used to generate the answer", example=["source1.txt", "source2.txt"])
    
    # Adds a complete example for the API docs
    class Config:
        schema_extra = {
            "example": {
                "answer": "To detect DCSync attacks, monitor for unusual replication requests and use tools like BloodHound to analyze permissions.",
                "sources": ["dcsync_detection_guide.pdf", "security_best_practices.docx", "BloodHound Edge Documentation", "MITE ATT&CK Framework"]
            }
        }